<a href="https://colab.research.google.com/github/mrsferret/Code-Division/blob/main/Worksheets/15_1_Encoding_and_Dummy_Coding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Encoding Data  
When we encode data, we remodel a numeric column in a dataframe to be on a standard scale (0 or 1).   
For example if we had a column of BMI scores, we could encode that column so that all scores greater than or equal to 25 were recoded to the value 1 (bad) and all scores less than 25 were recoded to 0 (good).  

For example:  

` def encode_bmi(df):`       
> `if df['bmi'] >= 25:`  
> >  `return 1`   

>`else`:  
> >`return 0`  

`df["bmi"] = df.apply(encode_bmi, axis=1)`

### Challenge 1 - prepare dataset for encoding 
---
1. Read Covid vaccination data from the `by_country` sheet in the Excel file at this link : https://github.com/lilaceri/Working-with-data-/blob/342abab10d93c4bf23b5c55a50f189f12a137c5f/Data%20Sets%20for%20code%20divisio/Covid%20Vaccination%20Data.xlsx?raw=true
2. Find out which columns have missing values
3. Remove all rows with missing data in the total_vaccination column  
4. Remove all rows with missing data in the daily_vaccinations_per_million 
4. find the median daily_vaccinations_per_million, storing this in a variable for use later     


**Test output**:  
1. dataframe is saved in a variable
2. 
```
RangeIndex: 14994 entries, 0 to 14993
Data columns (total 15 columns):
    Column                               Non-Null Count  Dtype         
                                
 0   country                              14994 non-null  object        
 1   iso_code                             14994 non-null  object        
 2   date                                 14994 non-null  datetime64[ns]
 3   total_vaccinations                   9011 non-null   float64       
 4   people_vaccinated                    8370 non-null   float64       
 5   people_fully_vaccinated              6158 non-null   float64       
 6   daily_vaccinations_raw               7575 non-null   float64       
 7   daily_vaccinations                   14796 non-null  float64       
 8   total_vaccinations_per_hundred       9011 non-null   float64       
 9   people_vaccinated_per_hundred        8370 non-null   float64       
 10  people_fully_vaccinated_per_hundred  6158 non-null   float64       
 11  daily_vaccinations_per_million       14796 non-null  float64       
 12  vaccines                             14994 non-null  object        
 13  source_name                          14994 non-null  object        
 14  source_website                       14994 non-null  object        
dtypes: datetime64[ns](1), float64(9), object(5)
memory usage: 1.7+ MB
```
3. 9011 rows Ã— 15 columns  
4. 8815 rows * 15 columns 
5. 6.65

In [1]:
import pandas as pd
url = "https://github.com/lilaceri/Working-with-data-/blob/342abab10d93c4bf23b5c55a50f189f12a137c5f/Data%20Sets%20for%20code%20divisio/Covid%20Vaccination%20Data.xlsx?raw=true"

# Task 2
def inspect_data(df):
  display("Describe: ", df.describe())
  display("Head: ", df.head())
  display("Info: ", df.info())

  # check the data for NA/NaN/missing values across the dataframe
  display("Null Values: ", df.isnull().values.any())

  cleaned_df = df

  return cleaned_df


# Task 3 & 4
def clean_data(df, col_name):

  # ================================================================
  # remove rows where column passed in as parm is null
  # ================================================================
  #
  clean_df = df[~df[col_name].isnull()]
  
  return clean_df
#=======================================================================
# Task 5
# find the median daily_vaccinations_per_million
#=======================================================================
def get_median(df):

  dly_vax_per_million_median = df['daily_vaccinations_per_million'].median()
  
  print("\ndly-vax_per_million_median = ", dly_vax_per_million_median)

  return dly_vax_per_million_median

#=======================================================================
# program starts here
#=======================================================================
# Task 1 - excel file into df
#=======================================================================
covid_vax_df = pd.read_excel(url)

#print ("\ndly_vax_per_million_median 1: ", covid_vax_df.median())
#min_total_vax = covid_vax_df[["country", "total_vaccinations"]].groupby("country").min()
#print(min_total_vax.to_string())

#=======================================================================
# Task 2 - inspect data
#=======================================================================
inspect_df = inspect_data(covid_vax_df)

#=======================================================================
# Task 3 - remove rows where total_vaccinations is empty
#=======================================================================
col_name = 'total_vaccinations'
covid_vax_df = clean_data(inspect_df, col_name)

display("Info after total_vaccinations drop na: ", covid_vax_df.info())

#=======================================================================
# Task 4 - remove rows where daily_vaccinations_per_million is empty
#=======================================================================
col_name = 'daily_vaccinations_per_million'
covid_vax_df = clean_data(covid_vax_df, col_name)

display("Info after daily_vaccinations_per_million drop na: ", covid_vax_df.info())

#=======================================================================
# Task 5
# find the median daily_vaccinations_per_million
#=======================================================================
median = get_median(covid_vax_df)

'Describe: '

,total_vaccinations,people_vaccinated,people_fully_vaccinated,daily_vaccinations_raw,daily_vaccinations,total_vaccinations_per_hundred,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,daily_vaccinations_per_million
count,9.011000e+03,8.370000e+03,6.158000e+03,7.575000e+03,1.479600e+04,9011.000000,8370.000000,6158.00000,14796.000000
mean,4.964584e+06,3.164030e+06,1.580482e+06,1.347569e+05,7.769163e+04,15.456079,11.228710,5.66235,2972.163625
std,2.033452e+07,1.180919e+07,6.840161e+06,5.211912e+05,3.519679e+05,23.238675,15.269686,10.06184,4720.846894
min,0.000000e+00,0.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,0.00000,0.000000
25%,6.000000e+04,5.154925e+04,2.350025e+04,2.888500e+03,8.967500e+02,1.330000,1.222500,0.63000,347.000000
50%,4.209400e+05,3.255035e+05,1.729175e+05,1.558300e+04,6.178500e+03,6.300000,4.825000,2.35000,1475.000000
75%,1.932222e+06,1.338161e+06,6.887102e+05,6.249850e+04,2.835000e+04,19.570000,14.667500,6.30000,3908.250000
max,2.753380e+08,1.470470e+08,1.047747e+08,1.160100e+07,7.205286e+06,211.080000,111.320000,99.76000,118759.000000

'Head: '

,country,iso_code,date,total_vaccinations,people_vaccinated,people_fully_vaccinated,daily_vaccinations_raw,daily_vaccinations,total_vaccinations_per_hundred,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,daily_vaccinations_per_million,vaccines,source_name,source_website
0,Afghanistan,AFG,2021-02-22,0.0,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,Oxford/AstraZeneca,Government of Afghanistan,https://reliefweb.int/report/afghanistan/afgha...
1,Afghanistan,AFG,2021-02-23,NaN,NaN,NaN,NaN,1367.0,NaN,NaN,NaN,35.0,Oxford/AstraZeneca,Government of Afghanistan,https://reliefweb.int/report/afghanistan/afgha...
2,Afghanistan,AFG,2021-02-24,NaN,NaN,NaN,NaN,1367.0,NaN,NaN,NaN,35.0,Oxford/AstraZeneca,Government of Afghanistan,https://reliefweb.int/report/afghanistan/afgha...
3,Afghanistan,AFG,2021-02-25,NaN,NaN,NaN,NaN,1367.0,NaN,NaN,NaN,35.0,Oxford/AstraZeneca,Government of Afghanistan,https://reliefweb.int/report/afghanistan/afgha...
4,Afghanistan,AFG,2021-02-26,NaN,NaN,NaN,NaN,1367.0,NaN,NaN,NaN,35.0,Oxford/AstraZeneca,Government of Afghanistan,https://reliefweb.int/report/afghanistan/afgha...

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14994 entries, 0 to 14993
Data columns (total 15 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   country                              14994 non-null  object
 1   iso_code                             14994 non-null  object
 2   date                                 14994 non-null  datetime64[ns]
 3   total_vaccinations                   9011 non-null   float64
 4   people_vaccinated                    8370 non-null   float64
 5   people_fully_vaccinated              6158 non-null   float64
 6   daily_vaccinations_raw               7575 non-null   float64
 7   daily_vaccinations                   14796 non-null  float64
 8   total_vaccinations_per_hundred       9011 non-null   float64
 9   people_vaccinated_per_hundred        8370 non-null   float64
 10  people_fully_vaccinated_per_hundred  6158 non-null   float64
 11  daily_vaccinations_per_million       14796 non-null  float64
 12  vaccines                             14994 non-null  object
 13  source_name                          14994 non-null  object
 14  source_website                       14994 non-null  object
dtypes: datetime64[ns](1), float64(9), object(5)
memory usage: 1.7+ MB

'Info: '

None

'Null Values: '

True

<class 'pandas.core.frame.DataFrame'>
Int64Index: 9011 entries, 0 to 14993
Data columns (total 15 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   country                              9011 non-null   object
 1   iso_code                             9011 non-null   object
 2   date                                 9011 non-null   datetime64[ns]
 3   total_vaccinations                   9011 non-null   float64
 4   people_vaccinated                    8294 non-null   float64
 5   people_fully_vaccinated              6157 non-null   float64
 6   daily_vaccinations_raw               7575 non-null   float64
 7   daily_vaccinations                   8816 non-null   float64
 8   total_vaccinations_per_hundred       9011 non-null   float64
 9   people_vaccinated_per_hundred        8294 non-null   float64
 10  people_fully_vaccinated_per_hundred  6157 non-null   float64
 11  daily_vaccinations_per_million       8816 non-null   float64
 12  vaccines                             9011 non-null   object
 13  source_name                          9011 non-null   object
 14  source_website                       9011 non-null   object
dtypes: datetime64[ns](1), float64(9), object(5)
memory usage: 1.1+ MB

'Info after total_vaccinations drop na: '

None

<class 'pandas.core.frame.DataFrame'>
Int64Index: 8816 entries, 6 to 14993
Data columns (total 15 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   country                              8816 non-null   object
 1   iso_code                             8816 non-null   object
 2   date                                 8816 non-null   datetime64[ns]
 3   total_vaccinations                   8816 non-null   float64
 4   people_vaccinated                    8126 non-null   float64
 5   people_fully_vaccinated              6143 non-null   float64
 6   daily_vaccinations_raw               7575 non-null   float64
 7   daily_vaccinations                   8816 non-null   float64
 8   total_vaccinations_per_hundred       8816 non-null   float64
 9   people_vaccinated_per_hundred        8126 non-null   float64
 10  people_fully_vaccinated_per_hundred  6143 non-null   float64
 11  daily_vaccinations_per_million       8816 non-null   float64
 12  vaccines                             8816 non-null   object
 13  source_name                          8816 non-null   object
 14  source_website                       8816 non-null   object
dtypes: datetime64[ns](1), float64(9), object(5)
memory usage: 1.1+ MB

'Info after daily_vaccinations_per_million drop na: '

None

dly-vax_per_million_median =  1915.5


---

**Notes from Challenge 1 cell above**

---

My output returns the same no. of records as expected for the size of the original dataset ie. 14994 rows and after task 3  (Task 3 remove rows where total_vaccinations is empty) ie. 9011 rows. However the expected output after task 4 (remove rows where daily_vaccinations_per_million is empty) says 8815 whereas my output returns 8816. 

There is also a difference in the actual median my code returned (1915.5) and the stated expected (6.65). 

I spent a bit of time debugging to try and work out what was causing the difference, but I suspect my values are correct. Looking at the values in the col `dly_vaccinations_per_million` , there is not any way that the median could realisticallu be 6.65. As regards the rows - I also think the expected output of recs given is also an error. When I looked at the expected row count for Challenge 2, it is given as 8816 ie. the same as what I get from my code.

### Challenge 2 - encode daily vaccinations 
---

Write a function to encode daily vaccinations per million, where values greater than or equal to median = 1 and values less than median = 0 

**Test output**: 

using describe()
```
count    8816.000000
mean        0.991493
std         0.091847
min         0.000000
25%         1.000000
50%         1.000000
75%         1.000000
max         1.000000
Name: daily_vaccinations_per_million, dtype: float64
```

In [2]:
#=======================================================================
# encode daily vaccinations per million, where values greater than or 
# equal to median = 1 and values less than median = 0
#=======================================================================
def encode_daily(df, **kwds):
  median = kwds['median']
  key = kwds['key']

  if df[key] >= median:
    return 1
  else:
    return 0

#=============================================================================
# Start
#=======================================================================
# get the median daily_vaccinations_per_million
#=======================================================================
median = get_median(covid_vax_df)
covid_vax_df["encoded"] = covid_vax_df.apply(encode_daily, axis = 1, key="daily_vaccinations_per_million", median=median)

covid_vax_df['encoded'].describe()

dly-vax_per_million_median =  1915.5

count    8816.000000
mean        0.500000
std         0.500028
min         0.000000
25%         0.000000
50%         0.500000
75%         1.000000
max         1.000000
Name: encoded, dtype: float64

### Challenge 3 - Encoding total vaccinations   
---
The United Kingdom has been praised for its fast vaccine rollout. 
1. Find the minimum total vaccinations for the United Kingdom 
2. Write a function to encode total_vaccinations column so that all values less than the UK's min are 0 and all values greater than or equal to the UK's min are coded as 1 
3. Display the unique countries for which total vaccinated is at the same rate or more than the UK

**Test output**:

1. 1402432.0
2. `df['total_vaccinations'].describe()` should output:
```
count    9011.00000
mean        0.29808
std         0.45744
min         0.00000
25%         0.00000
50%         0.00000
75%         1.00000
max         1.00000
Name: total_vaccinations, dtype: float64
```
3. 
```
array(['Argentina', 'Australia', 'Austria', 'Azerbaijan', 'Bangladesh',
       'Belgium', 'Brazil', 'Cambodia', 'Canada', 'Chile', 'China',
       'Colombia', 'Czechia', 'Denmark', 'Dominican Republic', 'England',
       'Finland', 'France', 'Germany', 'Greece', 'Hong Kong', 'Hungary',
       'India', 'Indonesia', 'Ireland', 'Israel', 'Italy', 'Japan',
       'Kazakhstan', 'Malaysia', 'Mexico', 'Morocco', 'Nepal',
       'Netherlands', 'Norway', 'Pakistan', 'Peru', 'Philippines',
       'Poland', 'Portugal', 'Qatar', 'Romania', 'Russia', 'Saudi Arabia',
       'Scotland', 'Serbia', 'Singapore', 'Slovakia', 'South Korea',
       'Spain', 'Sweden', 'Switzerland', 'Thailand', 'Turkey',
       'United Arab Emirates', 'United Kingdom', 'United States',
       'Uruguay', 'Wales'], dtype=object)
```

In [3]:
#=======================================================================
# Task 2 - encode total_vaccinations col:
# all values < UK min are 0 and otherwise coded as 1
#=======================================================================
def encode_total(df, **kwds):
  total = kwds['minimum']
  key = kwds['key']

  if df[key] >= total:
    return 1
  else:
    return 0

#=======================================================================
# Task 3 - Display the unique countries for which total vaccinated is 
# at the same rate or more than the UK
#=======================================================================
def display_unique_countries(df):
   
  unique_country = df.groupby('total_vaccinations_encoded').apply(lambda x: x['country'].unique())

  print(unique_country[1])

  return 

#=============================================================================
# Start
#=======================================================================
# Task 1 - find the min UK total_vaccinations 
#=======================================================================

minimum = covid_vax_df[covid_vax_df['country'] == 'United Kingdom'].total_vaccinations.min()

print("\nMin UK total Vax: ", minimum)

#=======================================================================
# Task 2 - encode total_vaccinations col:
# all values < UK min are 0 and otherwise coded as 1
#=======================================================================
covid_vax_df["total_vaccinations_encoded"] = covid_vax_df.apply(encode_total, 
                            axis = 1, key="total_vaccinations", minimum=minimum)

display(covid_vax_df['total_vaccinations_encoded'].describe())

#=======================================================================
# Task 3 - Display the unique countries for which total vaccinated is 
# at the same rate or more than the UK
#=======================================================================
display_unique_countries(covid_vax_df )

Min UK total Vax:  2677971.0

count    8816.000000
mean        0.214610
std         0.410575
min         0.000000
25%         0.000000
50%         0.000000
75%         0.000000
max         1.000000
Name: total_vaccinations_encoded, dtype: float64

['Argentina' 'Austria' 'Bangladesh' 'Belgium' 'Brazil' 'Canada' 'Chile'
 'China' 'Colombia' 'Czechia' 'England' 'France' 'Germany' 'Greece'
 'Hungary' 'India' 'Indonesia' 'Israel' 'Italy' 'Japan' 'Mexico' 'Morocco'
 'Netherlands' 'Poland' 'Portugal' 'Romania' 'Russia' 'Saudi Arabia'
 'Scotland' 'Serbia' 'South Korea' 'Spain' 'Sweden' 'Turkey'
 'United Arab Emirates' 'United Kingdom' 'United States']

---
**Notes from running Challenge 3 code cell**

---
This section caused me a fair bit of head scratching! 

My output from `df['total_vaccinations'].describe(`) is different to the listed expected. I don't think the expected output is correct as it expects the row count to be 9011. This is the original number of rows in the dataset, before we cleaned some of the rows with missing values.

My actual minimum `total_vaccinations` for the UK (2677971.0) is different from the expected value (1402432.0). I spent a bit of time checking that my minimum was correct and believe that it is.

Because of this, the countries I have returned for which total vaccinated is at the same rate or more than the UK is different from the predicted array eg. Australia is in the expected output but is not in my returned array. 

To validate my output, I double-checked the values of `total_vaccinations`for Australia in my dataframe. I found that the max value for `total_vaccinations` for Australia is 2254074.0. So if the min value for UK `total_vaccinations` is indeed 2677971.0 as my code calculated then Australia has correctly been excluded from my array.

In [4]:
print("\nMin UK total Vax: ", minimum)

max = covid_vax_df[covid_vax_df['country'] == 'Australia'].total_vaccinations.max()

print("\nAustralia max: ", max)

max_total_vax = covid_vax_df[["country", "total_vaccinations"]].groupby("country").max()
#print("\nmax_total_vax: ", max_total_vax)

Min UK total Vax:  2677971.0

Australia max:  2254074.0

### Challenge 4 - create new series of total vaccinations for each manufacturer
---

To create a new column in your dataframe:

`df['new_column'] = ...`

For example:

* to duplicate an existing column
  * `df['new_column'] = df['old_column']`
* to add two columns together 
  * `df['new_column'] = df['column1'] + df['column2']`
* to make a percentages column 
  * `df['new_column'] = (df['column1']/df['column1].sum()) * 100`

  
1. read data from 'by_manufacturer' sheet from Covid data 
2. find the sum of total vaccinations for each manufacturer
3. create a new column that has the total vaccinations as a percentage of the overall sum of total vaccinations 
4. find the median percentage 
5. create a new column called 'encoded_percentages' which duplicates the percentages column
6. encode the encoded_percentages column so that any values greater than or equal to the median percentage = 1 and any lesser than = 0 


**Test output**:

1.
2. 
```
vaccine
Johnson&Johnson        264839828
Moderna               5548036383
Oxford/AstraZeneca     539433203
Pfizer/BioNTech       8690461304
Sinovac                604660293
Name: total_vaccinations, dtype: int64
```
3. 
```
	location	date	vaccine	total_vaccinations	percentages
0	Chile	2020-12-24	Pfizer/BioNTech	420	0.000003
1	Chile	2020-12-25	Pfizer/BioNTech	5198	0.000033
2	Chile	2020-12-26	Pfizer/BioNTech	8338	0.000053
3	Chile	2020-12-27	Pfizer/BioNTech	8649	0.000055
4	Chile	2020-12-28	Pfizer/BioNTech	8649	0.000055
...	...	...	...	...	...
3291	United States	2021-05-01	Moderna	105947940	0.677095
3292	United States	2021-05-01	Pfizer/BioNTech	129013657	0.824504
3293	United States	2021-05-02	Johnson&Johnson	8374395	0.053519
3294	United States	2021-05-02	Moderna	106780082	0.682413
3295	United States	2021-05-02	Pfizer/BioNTech	130252779	0.832423
3296 rows Ã— 5 columns
```
4. 0.0011110194374896931
5. 
```
location	date	vaccine	total_vaccinations	percentage_of_total	encoded_percentages
0	Chile	2020-12-24	Pfizer/BioNTech	420	0.000003	0.000003
1	Chile	2020-12-25	Pfizer/BioNTech	5198	0.000033	0.000033
2	Chile	2020-12-26	Pfizer/BioNTech	8338	0.000053	0.000053
3	Chile	2020-12-27	Pfizer/BioNTech	8649	0.000055	0.000055
4	Chile	2020-12-28	Pfizer/BioNTech	8649	0.000055	0.000055
...	...	...	...	...	...	...
3291	United States	2021-05-01	Moderna	105947940	0.677095	0.677095
3292	United States	2021-05-01	Pfizer/BioNTech	129013657	0.824504	0.824504
3293	United States	2021-05-02	Johnson&Johnson	8374395	0.053519	0.053519
3294	United States	2021-05-02	Moderna	106780082	0.682413	0.682413
3295	United States	2021-05-02	Pfizer/BioNTech	130252779	0.832423	0.832423
3296 rows Ã— 6 columns
```
6. 
```
	location	date	vaccine	total_vaccinations	percentages	encode	encoded
0	Chile	2020-12-24	Pfizer/BioNTech	420	0.000003	0.000003	0
1	Chile	2020-12-25	Pfizer/BioNTech	5198	0.000033	0.000033	0
2	Chile	2020-12-26	Pfizer/BioNTech	8338	0.000053	0.000053	0
3	Chile	2020-12-27	Pfizer/BioNTech	8649	0.000055	0.000055	0
4	Chile	2020-12-28	Pfizer/BioNTech	8649	0.000055	0.000055	0
...	...	...	...	...	...	...	...
3291	United States	2021-05-01	Moderna	105947940	0.677095	0.677095	1
3292	United States	2021-05-01	Pfizer/BioNTech	129013657	0.824504	0.824504	1
3293	United States	2021-05-02	Johnson&Johnson	8374395	0.053519	0.053519	1
3294	United States	2021-05-02	Moderna	106780082	0.682413	0.682413	1
3295	United States	2021-05-02	Pfizer/BioNTech	130252779	0.832423	0.832423	1
3296 rows Ã— 7 columns
```

In [17]:

#=======================================================================
# Task 2 - find the sum of total vaccinations for each manufacturer
#=======================================================================
def calc_sum_per_mnfctr(df):
  sum_total_vax = df[["vaccine", "total_vaccinations"]].groupby("vaccine").sum()
  #print(sum_total_vax.to_string())

  return sum_total_vax

#=======================================================================
# Task 3 - create new col with total vaccinations as a % overall sum of 
# total vaccinations
#=======================================================================
def create_new_col(df):

  df['percent_total_sum_vax'] = (df['total_vaccinations']/df['total_vaccinations'].sum()) * 100
 
  return df
#=======================================================================
# Task 4
# find the median percent_total_sum_vax
#=======================================================================
def calc_median(df):

  median_percent = df['percent_total_sum_vax'].median()
  
  #print("\median_percent = ", median_percent)

  return median_percent

#=======================================================================
# Task 5 - encode percent_total_sum_vax col:
# all values >= median percentage = 1 and otherwise coded as 0
#=======================================================================
def encode_total(df, **kwds):
  total = kwds['median']

  key = kwds['key']

  if df[key] >= total:
    return 1
  else:
    return 0

#=======================================================================
# program starts here
#=======================================================================
# Task 1 - read excel file into df
#=======================================================================

url = "https://github.com/lilaceri/Working-with-data-/blob/342abab10d93c4bf23b5c55a50f189f12a137c5f/Data%20Sets%20for%20code%20divisio/Covid%20Vaccination%20Data.xlsx?raw=true"
covid_vax_by_mnfctr_df = pd.read_excel(url,sheet_name="by_manufacturer")

display (covid_vax_by_mnfctr_df.columns)

#=======================================================================
# Task 2 - find the sum of total vaccinations for each manufacturer
#=======================================================================
sum_total_vax = calc_sum_per_mnfctr(covid_vax_by_mnfctr_df)

print(sum_total_vax.to_string())

#=======================================================================
# Task 3 - create new col with total vaccinations as a % overall sum of 
# total vaccinations
#=======================================================================

covid_vax_by_mnfctr_new_df = create_new_col(covid_vax_by_mnfctr_df)

print("\ncovid_vax_by_mnfctr_new_df: ", covid_vax_by_mnfctr_new_df.columns)

#=======================================================================
# Task 4 - find median percentage of new col percent_total_sum_vax
#=======================================================================

median_percent = calc_median(covid_vax_by_mnfctr_new_df)

print("\nmedian percent: ", median_percent, "\n\n")

#=======================================================================
# Task 5 - encode percent_total_sum_vax col:
#=======================================================================
covid_vax_by_mnfctr_new_df["encoded_percentages"] = covid_vax_by_mnfctr_new_df.apply(encode_total, axis = 1, 
                              key="percent_total_sum_vax", median=median_percent)

display(covid_vax_by_mnfctr_new_df)

Index(['location', 'date', 'vaccine', 'total_vaccinations'], dtype='object')

                    total_vaccinations
vaccine
Johnson&Johnson              264839828
Moderna                     5548036383
Oxford/AstraZeneca           539433203
Pfizer/BioNTech             8690461304
Sinovac                      604660293

covid_vax_by_mnfctr_new_df:  Index(['location', 'date', 'vaccine', 'total_vaccinations',
       'percent_total_sum_vax'],
      dtype='object')

median percent:  0.0011110194374896931

,location,date,vaccine,total_vaccinations,percent_total_sum_vax,encoded_percentages
0,Chile,2020-12-24,Pfizer/BioNTech,420,0.000003,0
1,Chile,2020-12-25,Pfizer/BioNTech,5198,0.000033,0
2,Chile,2020-12-26,Pfizer/BioNTech,8338,0.000053,0
3,Chile,2020-12-27,Pfizer/BioNTech,8649,0.000055,0
4,Chile,2020-12-28,Pfizer/BioNTech,8649,0.000055,0
...,...,...,...,...,...,...
3291,United States,2021-05-01,Moderna,105947940,0.677095,1
3292,United States,2021-05-01,Pfizer/BioNTech,129013657,0.824504,1
3293,United States,2021-05-02,Johnson&Johnson,8374395,0.053519,1
3294,United States,2021-05-02,Moderna,106780082,0.682413,1
3295,United States,2021-05-02,Pfizer/BioNTech,130252779,0.832423,1

# Reflection
----

## What skills have you demonstrated in completing this notebook?

Your answer:

## What caused you the most difficulty?

I found Task 3 the most difficult ie. to display the unique countries for which total vaccinated is at the same rate or more than the UK. 

I initially went down the track of using `groupby` to get the max value per country but couldn't work out how to only select countries where that max was >= UK mininum. Then of course, I realised that I should just be the using the new column I had just created `total_vaccinations_encoded` as that already told me if the country's `total_vaccinations` were greater then UK min! My problem then was to get unique country names as there was generally more than 1 row per country in the dataset. I struggled trying different combinations and permutations of `groupby` as well as numpy `where` but couldn't get the output needed. Eventually after speaking to Tiffany, she supplied me with code that would work. This was my first time using the lambda function so it took a little while for me to understand what the code was doing. 

Firstly, it seemed counter intuitive to me to `groupby` the new encoded column `'total_vaccinations_encoded'` and not `country` but then realised that it was effectively sorting the dataframe into the 2 groups - countries where total vaccinations > than the UK minimum and those that were not. Then, where the country appeared more than once in the group, by using `.unique`, this was effectively filtering out the unique countries to give the final list. I'm not sure I would have been able to figure this out myself, but i working out how exactly the code works, I've certainly have learnt alot about using `groupby`, `apply` and `lambda` which I'm sure will be very useful to me.